export const SET_USER_NAME = "CURRENT_USER/SET_NAME"
export const SET_USER_ID = "CURRENT_USER/SET_ID"
export const FETCH_USER_AVATAR = "CURRENT_USER/FETCH_AVATAR"

export const SHOW_LOCK_SPINNER = "APP/SHOW_LOCK_SPINNER"
export const HIDE_LOCK_SPINNER = "APP/HIDE_LOCK_SPINNER"

export const SHOW_LOBBY_CREATING_SPINNER = "APP/SHOW_LOBBY_CREATING_SPINNER"
export const HIDE_LOBBY_CREATING_SPINNER = "APP/HIDE_LOBBY_CREATING_SPINNER"

export const CHANGE_INPUT_GAME_ID = "APP/CHANGE_INPUT_GAME_ID"

export const CREATE_GAME = "GAME/CREATE_GAME"
export const JOIN_GAME = "GAME/JOIN_GAME"

export const SET_GAME_DATA = "GAME/SET_GAME_DATA"
export const SET_CURRENT_USER = "GAME/SET_CURRENT_USER"

export const PLAYERS_UPDATED = "GAME/PLAYERS_UPDATED"
export const SET_GAME_READY = "APP/SET_GAME_READY" // Кароче если true - редирект будет сразу в лобби

export const KICK_PLAYER = "GAME/KICK_PLAYER"

export const UPDATE_SETTINGS = "GAME/UPDATE_SETTINGS"
export const SETTINGS_UPDATED = "GAME/SETTINGS_UPDATED"

export const SET_GS_ALLOW_FOREIGN = "GAME/SETTINGS/ALLOW_FOREIGN"

export const LOAD_OPEN_GAMES = "APP/LOAD_OPEN_GAMES"
export const SET_OPEN_GAMES = "APP/SET_OPEN_GAMES"

export const START_GAME = "GAME/START_GAME"

export const SET_GAME_TIMER = "GAME/SET_GAME_TIMER"
