export const SET_USER_NAME = "CURRENT_USER/SET_NAME"
export const FETCH_USER_AVATAR = "CURRENT_USER/FETCH_AVATAR"
export const SHOW_AVATAR_LOADING = "APP/SHOW_AVATAR_LOADING"
export const HIDE_AVATAR_LOADING = "APP/HIDE_AVATAR_LOADING"
